package com.vista.Cotizaciones;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Link;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CotizacionView extends FormLayout {
	protected Link auditoria;
	protected TextField codMoneda;
	protected TextField descripcionMoneda;
	protected Button btnBuscarMoneda;
	protected DateField fecha;
	protected TextField cotizacionCompra;
	protected TextField cotizacionVenta;
	protected Button aceptar;
	protected Button btnEditar;
	protected Button cancelar;

	public CotizacionView() {
		Design.read(this);
	}
}
