package com.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CotizacionView extends CssLayout {
	protected Label billing_header_label;
	protected CssLayout main_content_wrapper;
	protected FormLayout billing_form;
	protected Label cotizacion_header_label;
	protected DateField fecha;
	protected ComboBox codMoneda;
	protected TextField impVenta;
	protected TextField impCompra;
	protected Button btnIngresar;

	public CotizacionView() {
		Design.read(this);
	}
}
