package com.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GrupoFormularioPermisos extends FormLayout {
	protected Label lbDescripcion;
	protected CheckBox chkLeer;
	protected CheckBox chkNuevoEditar;
	protected CheckBox chkEliminar;
	protected Button btnAgregar;
	protected Button cancelar;

	public GrupoFormularioPermisos() {
		Design.read(this);
	}
}
