package com.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Menu extends HorizontalLayout {
	protected HorizontalLayout menuTitle;
	protected Label menuTitleLabel;
	protected Button logoutButton;
	protected Button menuToggle;
	protected CssLayout menuItems;
	protected Label lbMantenimientos;
	protected Button userButton;
	protected Button funcionariosButton;
	protected Button gruposButton;
	protected Button impuestoButton;
	protected Button empresaButton;
	protected Button monedasButton;
	protected Button documentosButton;
	protected Button clientesButton;
	protected Button codigosGeneralizados;
	protected Button rubros;
	protected Label lbCobros;
	protected Label lbFacturacion;
	protected Label lbProcesos;
	protected Label lbAdministracion;
	protected Button cotizaciones;
	protected Button tipoRubros;
	protected Button cuentas;
	protected Button bancos;
	protected Button procesos;
	protected Button gastos;
	protected Button ingCobro;
	protected Button ingEgreso;
	protected Button otroCobro;
	protected Button otroEgreso;
	protected Button resumenProc;
	protected Button factura;
	protected Button recibo;
	protected Button notaCredito;
	protected Button periodo;
	protected Button deposito;
	protected Button conciliacion;
	protected Label lbReportes;
	protected Button btnRepCheque;
	protected Button btnRepGastosPendCobro;
	protected Button btnCheqADepositar;
	protected Button btnRepIva;
	protected Button btnRepGastosxProceso;
	protected Button btnEstadoCuenta;
	protected Button btnEstadoCuentaTotales;
	protected Button btnMovPorCuenta;
	protected Button btnMovPorRubro;
	protected Button btnMovCaja;
	protected Button btnMovBco;
	protected VerticalLayout content;

	public Menu() {
		Design.read(this);
	}
}
