package com.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Menu extends HorizontalLayout {
	protected HorizontalLayout menuTitle;
	protected Label menuTitleLabel;
	protected Button menuToggle;
	protected CssLayout menuItems;
	protected Button userButton;
	protected Button funcionariosButton;
	protected Button gruposButton;
	protected Button logoutButton;
	protected Button impuestoButton;
	protected Button empresaButton;
	protected Button monedasButton;
	protected Button documentosButton;
	protected Button clientesButton;
	protected Button codigosGeneralizados;
	protected Button rubros;
	protected Accordion acordion;
	protected VerticalLayout content;

	public Menu() {
		Design.read(this);
	}
}
