package com.vista.Gastos;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Link;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GastoView extends CssLayout {
	protected CssLayout main_content_wrapper;
	protected FormLayout billing_form;
	protected TextField codGasto;
	protected DateField fecha;
	protected Link auditoria;
	protected HorizontalLayout proceso;
	protected TextField codProceso;
	protected TextField codCliente;
	protected TextField nomCliente;
	protected Button btnBuscarProceso;
	protected TextField codRubro;
	protected TextField descripcionRubro;
	protected TextField descripcionImpuesto;
	protected TextField porcentajeImpuesto;
	protected TextField codImpuesto;
	protected ComboBox comboImpuesto;
	protected Button btnBuscarRubro;
	protected TextField codCuenta;
	protected TextField descripcionCuenta;
	protected Button btnBuscarCuenta;
	protected ComboBox comboMoneda;
	protected TextField tcMov;
	protected HorizontalLayout importe;
	protected TextField impMo;
	protected TextField impMn;
	protected TextField impTr;
	protected TextField descripcion;
	protected Button aceptar;
	protected Button btnEditar;
	protected Button cancelar;

	public GastoView() {
		Design.read(this);
	}
}
