package com.vista.Reportes.EstadoCuentaTotales;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RepEstadoCuentaTotalesViews extends FormLayout {
	protected FormLayout formLay12;
	protected TextField nroTrans;
	protected DateField fecDesde;
	protected DateField fecHasta;
	protected HorizontalLayout botones;
	protected Button aceptar;

	public RepEstadoCuentaTotalesViews() {
		Design.read(this);
	}
}
